# -*- coding: utf-8 -*-
"""Synapse Task2

Automatically generated by Colaboratory.

Original file is located at https://colab.research.google.com/drive/1nN7c8TH_7GZLAWRbdEAazOtADrHhcySy
(Only cleaning part on colab due to lack of gui)
"""
import pandas as pd
from pandasgui import show

# Original Data
orig_df = pd.read_json('./data.json')
data = pd.DataFrame([col for col in orig_df.data])
data = pd.concat([data.drop(['location'], axis=1),
                  data['location'].apply(pd.Series)], axis=1)

# Drop unneeded data
data = data.drop(columns=['marital_status'])

# Remove aged users
data = data[(data['age'] != '45-54') & (data['age'] != '55+')]
#data = data.drop(columns='age')

# Filtering non-compatible categories
data = data[(data['category'] == 'Environment')
            | (data['category'] == 'Sports')]
#data = data.drop(columns='category')

# Only keep most valuable entries from each user
ids = []
cat = []
evt = []
dup = []

for ind in data.index:
    try:
        loc = ids.index(data['session_id'][ind])
        if evt[loc] == 'Fund Project' and data['event_name'][ind] == 'Fund Project':
            pass  # check for prices here if needed
        elif evt[loc] == 'Fund Project':
            dup.append(ind)
        elif data['event_name'][ind] == 'Fund Project':
            # Remove view item
            ids.pop(loc)
            cat.pop(loc)
            evt.pop(loc)
            # Add Fund item
            ids.append(data['session_id'][ind])
            cat.append(data['category'][ind])
            evt.append(data['event_name'][ind])
        else:
            dup.append(ind)
    except ValueError:
        ids.append(data['session_id'][ind])
        cat.append(data['category'][ind])
        evt.append(data['event_name'][ind])
    except Exception as e:
        print(e)

data = data.drop(index=dup)

# Visualisation
show(data, settings={'block': True})
